#pragma once
// This file is generated by builder/vmloader_builder at build time.
// Run: make embedded  (or just: make)
// Do not edit by hand.
//
// Expected symbols after generation:
//   inline constexpr unsigned char    g_vm_ir_blob[]      = { ... };
//   inline constexpr std::uint32_t    g_vm_ir_seed        = 0x...;
//   inline constexpr unsigned char    g_vm_payload[]      = { ... };
//   inline constexpr std::size_t      g_vm_payload_size   = ...;
//
// Placeholder - real values injected by vmloader_builder.
#include <cstddef>
#include <cstdint>
inline constexpr unsigned char  g_vm_ir_blob[]    = { 0x00 };
inline constexpr std::uint32_t  g_vm_ir_seed      = 0x00000000u;
inline constexpr unsigned char  g_vm_payload[]    = { 0x00 };
inline constexpr std::size_t    g_vm_payload_size = 0;
